# Generated by Django 3.0.7 on 2020-07-03 13:48

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('directorName', models.CharField(db_column='director_name', max_length=250)),
                ('img_location', models.FilePathField(path=home.models.images_path)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
    ]
