# Generated by Django 3.0.7 on 2020-07-03 15:22

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('imgLocation', models.FilePathField(db_column='img_location', path=home.models.images_path)),
                ('artistType', models.CharField(choices=[('singer', 'Singer'), ('writer', 'Writer'), ('composer', 'Conposer')], db_column='artist_type', max_length=50)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('musicCompany', models.CharField(db_column='music_company', max_length=250)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('under_review', 'under_review'), ('published', 'published'), ('change_request', 'change_request'), ('declined', 'declined')], default='draft', max_length=50)),
                ('genere', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'lyrics',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lableType', models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator'), ('collaborator', 'Collaborator')], db_column='lable_type', default='collaborator', max_length=50)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.RenameField(
            model_name='album',
            old_name='img_location',
            new_name='imgLocation',
        ),
        migrations.AlterField(
            model_name='album',
            name='imgLocation',
            field=models.FilePathField(db_column='img_location', path=home.models.images_path),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=20)),
                ('fullName', models.CharField(db_column='full_name', max_length=250)),
                ('roleId', models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.UserRole')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='LyricEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('declined', 'declined'), ('published', 'published')], default='created', max_length=50)),
                ('ocurredAt', models.DateTimeField(db_column='ocurred_at')),
                ('userEmail', models.CharField(db_column='user_email', max_length=100)),
                ('lyricId', models.ForeignKey(db_column='lyric_id', on_delete=django.db.models.deletion.CASCADE, to='home.Lyric')),
            ],
            options={
                'db_table': 'lyrics_events',
            },
        ),
        migrations.AddField(
            model_name='lyric',
            name='albumId',
            field=models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='home.Album'),
        ),
        migrations.AddField(
            model_name='lyric',
            name='userId',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistId', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Artist')),
                ('lyricId', models.ForeignKey(db_column='lyric_id', on_delete=django.db.models.deletion.CASCADE, to='home.Lyric')),
            ],
            options={
                'db_table': 'artist_songs',
            },
        ),
    ]
