# Generated by Django 3.0.7 on 2020-07-09 16:43

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200703_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='imgg',
            field=models.ImageField(db_column='imgg_test', null=True, upload_to=home.models.images_path),
        ),
    ]
