# Generated by Django 3.0.7 on 2020-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_album_imgg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='imgg',
        ),
        migrations.AlterField(
            model_name='album',
            name='imgLocation',
            field=models.ImageField(db_column='img_location', null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='imgLocation',
            field=models.ImageField(db_column='img_location', null=True, upload_to='static/images'),
        ),
    ]
