# Generated by Django 3.0.7 on 2020-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200709_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
