# Generated by Django 3.0.7 on 2020-07-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_lyric_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='name',
            field=models.CharField(default='dafault', max_length=250),
            preserve_default=False,
        ),
    ]
