# Generated by Django 3.0.7 on 2020-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_lyric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imgLocation',
            field=models.ImageField(db_column='img_location', null=True, upload_to='static/images/albums'),
        ),
    ]
