# Generated by Django 3.0.7 on 2020-07-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200723_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='name',
            new_name='title',
        ),
    ]
