# Generated by Django 3.0.7 on 2020-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200723_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='imgLocation',
            field=models.ImageField(db_column='img_location', null=True, upload_to='static/images/artists'),
        ),
    ]
